"use client";
import { useEffect, useState, useCallback } from "react";
import { useSearchParams } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { FileText, Sparkles, AlertCircle, Loader2 } from "lucide-react";
import { useAppDataStore } from "@/stores";
import { ExportBar } from "@/components/dashboard/ExportBar";
import { useToast } from "@/hooks/use-toast";
import { useErrorNotification } from "@/hooks/useErrorNotification";
import { useSubscriptionStore } from "@/stores/subscriptionStore";
import { useAutosave } from "@/hooks/useAutosave";
import { AutosaveIndicator } from "@/components/ui/autosave-indicator";
import { HelpTooltip } from "@/components/ui/help-tooltip";
import { ResumePreview } from "@/components/common/ResumePreview";
import { ProgressIndicator } from "@/components/ui/progress-indicator";

export const StepResume = () => {
  const [searchParams] = useSearchParams();
  const [hasAutoGenerated, setHasAutoGenerated] = useState(false);
  const {
    settings,
    inputs,
    outputs,
    updateSettings,
    updateInputs,
    generateResume,
    status,
    generationProgress
  } = useAppDataStore();
  const { toast } = useToast();
  const { showResumeGenerationError, showSuccess } = useErrorNotification();
  const { hasReachedMonthlyLimit, getMonthlyGenerationLimit } = useSubscriptionStore();

  // Autosave functionality
  const autosaveData = { 
    inputs, 
    settings,
    timestamp: new Date().toISOString()
  };
  
  const {
    isSaving: isAutosaving,
    lastSaved,
    hasUnsavedChanges,
    error: autosaveError,
    forceSave
  } = useAutosave(
    autosaveData,
    async (data) => {
      // Save to localStorage as draft
      const draftKey = 'resume_builder_draft';
      localStorage.setItem(draftKey, JSON.stringify(data));
    },
    {
      delay: 1500, // Save after 1.5 seconds of inactivity
      enabled: true,
      showNotification: false // We'll show our own indicator
    }
  );

  // Handle autostart generation when component mounts
  useEffect(() => {
    const autostart = searchParams.get('autostart');
    const hasInputs = inputs.resumeText?.trim() && inputs.jobText?.trim();
    const hasOutput = outputs?.resume?.trim();
    
    if (autostart === '1' && hasInputs && !hasOutput && !status.loading && !hasAutoGenerated) {
      // Small delay to ensure component is fully mounted
      const timer = setTimeout(() => {
        handleGenerate();
        setHasAutoGenerated(true);
      }, 100);
      
      return () => clearTimeout(timer);
    }
  }, [searchParams, inputs.resumeText, inputs.jobText, outputs?.resume, status.loading, hasAutoGenerated, handleGenerate]);

  const resume = outputs?.resume ?? "";
  const words = (resume.trim().match(/\S+/g) || []).length;
  const canContinue = words > 0 && words <= 550;

  const handleGenerate = useCallback(async () => {
    if (!inputs.resumeText.trim() || !inputs.jobText.trim()) {
      toast({
        title: "Missing Inputs",
        description: "Please provide both resume content and job description.",
        variant: "destructive",
      });
      return;
    }

    // Check monthly generation limit for free users
    if (hasReachedMonthlyLimit()) {
      toast({
        title: "Monthly Limit Reached",
        description: `You've reached your limit of ${getMonthlyGenerationLimit()} resume generations this month. Upgrade to Pro for unlimited generations.`,
        variant: "destructive",
      });
      return;
    }

    try {
      console.log('Starting resume generation from StepResume...');
      await generateResume();
      showSuccess("Your targeted resume has been created successfully!", {
        title: "Resume Generated!",
        action: {
          label: "View",
          onClick: () => {
            const previewElement = document.getElementById('resume-preview');
            previewElement?.scrollIntoView({ behavior: 'smooth' });
          }
        }
      });
    } catch (error) {
      console.error('Resume generation error:', error);
      showResumeGenerationError(() => handleGenerate());
    }
  }, [inputs.resumeText, inputs.jobText, generateResume, toast, showSuccess, showResumeGenerationError, hasReachedMonthlyLimit, getMonthlyGenerationLimit]);

  return (
    <div className="grid lg:grid-cols-2 gap-8 p-8">
      {/* Input Section */}
      <div className="space-y-6">
        <div className="flex items-start justify-between mb-6">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 bg-gradient-to-br from-primary to-accent rounded-xl flex items-center justify-center">
              <FileText className="w-5 h-5 text-white" />
            </div>
            <div>
              <h2 className="text-2xl font-bold text-foreground">Generate Resume</h2>
              <p className="text-muted-foreground">Create an ATS-optimized resume for your target job</p>
            </div>
          </div>
          
          {/* Autosave Indicator */}
          <AutosaveIndicator
            isSaving={isAutosaving}
            lastSaved={lastSaved}
            hasUnsavedChanges={hasUnsavedChanges}
            error={autosaveError}
            onForceSave={forceSave}
          />
        </div>

        {/* Settings */}
        <Card className="bg-muted/30">
          <CardHeader>
            <CardTitle className="flex items-center gap-2 text-lg">
              Configuration
              <HelpTooltip 
                content="These settings control how your resume is generated. Choose options that best match your experience level and the job you're targeting."
                variant="tip"
              />
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div className="space-y-2">
                <div className="flex items-center gap-1">
                  <Label htmlFor="mode">Resume Mode</Label>
                  <HelpTooltip 
                    content="Concise: Best for entry-level or career changers (≤350 words). Detailed: For experienced professionals (≤550 words). Executive: For senior leadership roles (≤450 words)."
                    variant="info"
                  />
                </div>
                <Select value={settings.mode} onValueChange={(value) => updateSettings({ mode: value as any })}>
                  <SelectTrigger>
                    <SelectValue placeholder="Select mode" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="concise">Concise (≤350 words)</SelectItem>
                    <SelectItem value="detailed">Detailed (≤550 words)</SelectItem>
                    <SelectItem value="executive">Executive (≤450 words)</SelectItem>
                  </SelectContent>
                </Select>
              </div>

              <div className="space-y-2">
                <div className="flex items-center gap-1">
                  <Label htmlFor="voice">Voice Style</Label>
                  <HelpTooltip 
                    content="First Person: Uses 'I developed...' - more personal and engaging. Third Person: Uses 'Developed...' - traditional and formal style preferred by some industries."
                    variant="info"
                  />
                </div>
                <Select value={settings.voice} onValueChange={(value) => updateSettings({ voice: value as any })}>
                  <SelectTrigger>
                    <SelectValue placeholder="Select voice" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="first-person">First Person</SelectItem>
                    <SelectItem value="third-person">Third Person</SelectItem>
                  </SelectContent>
                </Select>
              </div>
            </div>

            <div className="flex items-center justify-between">
              <div className="space-y-1">
                <div className="flex items-center gap-1">
                  <Label>Include Skills Table</Label>
                  <HelpTooltip 
                    content="Adds a structured skills section with technical and soft skills organized in a clean table format. Recommended for technical roles."
                    variant="info"
                  />
                </div>
                <p className="text-xs text-muted-foreground">Add structured skills section</p>
              </div>
              <Switch
                checked={settings.includeTable}
                onCheckedChange={(checked) => updateSettings({ includeTable: checked })}
              />
            </div>
          </CardContent>
        </Card>

        {/* Resume Input */}
        <div className="space-y-2">
          <Label htmlFor="resume">Current Resume Content</Label>
          <Textarea
            id="resume"
            placeholder="Paste your current resume content here..."
            value={inputs.resumeText}
            onChange={(e) => updateInputs({ resumeText: e.target.value })}
            className="min-h-[200px]"
          />
          <p className="text-sm text-muted-foreground">
            {inputs.resumeText.length} characters (minimum 50 required)
          </p>
        </div>

        {/* Job Description Input */}
        <div className="space-y-2">
          <Label htmlFor="job">Target Job Description</Label>
          <Textarea
            id="job"
            placeholder="Paste the complete job description here..."
            value={inputs.jobText}
            onChange={(e) => updateInputs({ jobText: e.target.value })}
            className="min-h-[200px]"
          />
          <p className="text-sm text-muted-foreground">
            {inputs.jobText.length} characters (minimum 50 required)
          </p>
        </div>

        {/* Generate Button */}
        <Button
          onClick={async () => {
            await handleGenerate();
          }}
          disabled={status.loading || !inputs.resumeText.trim() || !inputs.jobText.trim()}
          className="w-full bg-gradient-to-r from-primary to-accent text-white hover:scale-105 transition-transform"
          size="lg"
        >
          {status.loading ? (
            <>
              <Loader2 className="mr-2 h-4 w-4 animate-spin" />
              Generating Resume...
            </>
          ) : (
            <>
              <Sparkles className="mr-2 h-4 w-4" />
              Generate Resume
            </>
          )}
        </Button>

        {/* Progress Indicator */}
        {status.loading && (
          <ProgressIndicator
            phases={generationProgress.phases.map(p => ({
              ...p,
              estimatedDuration: 15 // Default 15 seconds per phase
            }))}
            currentPhase={generationProgress.phase}
            totalProgress={generationProgress.progress}
            showDetails={true}
            className="mt-4"
          />
        )}
      </div>

      {/* Preview Section */}
      <div id="resume-preview" className="space-y-4">
        <div className="flex items-center justify-between">
          <h3 className="text-lg font-semibold">Resume Preview</h3>
          {resume && (
            <div className="flex items-center gap-2">
              <Badge variant={canContinue ? "secondary" : "destructive"}>
                {words}/550 words
              </Badge>
              {!canContinue && (
                <AlertCircle className="w-4 h-4 text-destructive" />
              )}
            </div>
          )}
        </div>
        {!canContinue && words > 550 && (
          <p className="text-sm mt-2" style={{color:'#FF851B'}}>Over 550 words — trim to continue.</p>
        )}

        <Card className="bg-muted/30">
          <CardContent className="p-6 space-y-4">
            <ResumePreview />
            {!status.loading && resume.trim() && (
              <ExportBar content={resume} filename="targeted-resume" />
            )}
          </CardContent>
        </Card>
      </div>
    </div>
  );
};
