// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://whfmypoeliexhdoiyvkv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndoZm15cG9lbGlleGhkb2l5dmt2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0NTgwMzksImV4cCI6MjA3MTAzNDAzOX0.T23kr94lHF5Irrj5Kqeft4aT-kEiE5mj7IgHM1vPAH0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});